config/routes.rb
Blog::Application.routes.draw do

  get "/tweets", to: "posts#tweets"
  	devise_for :users

	devise_scope :user do
	  get "register", to: "devise/registrations#new"
	  get "login", to: "devise/sessions#new"
	  get "logout", to: "devise/sessions#destroy"
	end

	resources :posts do
	  resources :comments
	end

	root "posts#index"

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  commenter  :string(255)
#  body       :text
#  post_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Comment < ActiveRecord::Base
  belongs_to :post

  validates :body, :commenter, presence: true
  
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	belongs_to :user
	
	validates :title, presence: true
	validates :content, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	        :recoverable, :rememberable, :trackable, :validatable

  	has_many :posts

	validates :first_name, presence: true
	validates :last_name, presence: true

	def full_name
		[first_name, last_name].join(" ")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!, only: [:new, :create, 
  							:edit, :update, :delete, :destroy]

  							
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
	    @post = Post.find(params[:post_id])
	    @comment = @post.comments.create(comment_params)
	    redirect_to post_path(@post)
 	end

 	def destroy
 		@post = Post.find(params[:post_id])
 		@comment = @post.comments.find(params[:id])
 		@comment.destroy
 		redirect_to post_path(@post)
 	end

	private

	def comment_params
    	params.require(:comment).permit(:commenter, :body)
    	
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :get_post, only: [:edit, :update, :delete, :destroy, :show]
	require 'twitter'

	def tweets
		@client = Twitter::REST::Client.new do |config|
			config.consumer_key        = ENV["CONSUMER_KEY"]
			config.consumer_secret     = ENV["CONSUMER_SECRET"]
			config.access_token        = ENV["ACCESS_TOKEN"]
			config.access_token_secret = ENV["ACCESS_SECRET"]
		end
	end

	def index
		@posts = Post.all.order(updated_at: :desc)
		respond_to do |format|
    		format.html
    		format.json { render json: @posts }
    	end
	end

	def show
    	respond_to do |format|
    		format.html
    		format.json { render json: @post }
    	end
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		respond_to do |format|
			if @post.save
				format.html { redirect_to @post, notice: "Post successfully created!" }
	        	format.json { render action: 'show', status: :created, location: @post }
			else
				format.html { render action: 'new' }
		        format.json { render json: @post.errors, status: :unprocessable_entity }
			end
		end
	end

	def edit
	end

	def update
		respond_to do |format|
			if  @post.update(post_params)
				format.html { redirect_to @post, notice: 'Post was successfully updated.' }
		        format.json { head :no_content }
			else
				format.html { render :edit }
	        	format.json { render json: @post.errors, status: :unprocessable_entity }
			end
		end
	end

	def delete
	end

	def destroy
		@post.destroy
		respond_to do |format|
      		format.html { redirect_to posts_path }
      		format.json { head :no_content }
		end
	end

	def get_post
		@post = Post.find(params[:id])
	end


	private

	def post_params
    	params.require(:post).permit(:title, :content)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	ActionView::Helpers::UrlHelper

	require 'rss'
	require 'open-uri'

	def gravatar_for(user)
		gravatar_id = Digest::MD5.hexdigest(user)
	    "http://gravatar.com/avatar/#{gravatar_id}.png"
	end

	def flash_class (type)
		case type
		when :notice
			"alert-success"
		when :alert
			"alert-error"
		else
			""
		end
	end

	def blog_feed
		url = "http://feeds.mashable.com/mashable/tech"
		rss = RSS::Parser.parse(url, false)
		link_to rss.items.first.title, rss.items.first.link 
	end

	def login(user)
		if  user_signed_in?
			link_to 'Logout', logout_path 
		else
			link_to 'Login', login_path 
		end 
	end

	def edit_profile(user)
		link_to 'Edit Profile', edit_user_registration_path if user_signed_in?
	end
end

	

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	ActionView::Helpers::UrlHelper

	def markdown(content)
		extensions = {
			hard_wrap: true, 
			filter_html: true, 
			autolink: true, 
			no_intraemphasis:true, 
			fenced_code_blocks: true,
			superscript: true
		}

		options = {
	      filter_html: true,
	      hard_wrap: true, 
	      space_after_headers: true, 
	      fenced_code_blocks: true,
	      prettify: true
	  }
		renderer = Redcarpet::Render::HTML.new(options)
		markdown = Redcarpet::Markdown.new(renderer, extensions)
		markdown.render(content)
	end

end

app/helpers/tweets_helper.rb
module TweetsHelper
	require 'twitter'

	@client = Twitter::REST::Client.new do |config|
	  config.consumer_key    = ENV["CONSUMER_KEY"]
	  config.consumer_secret = ENV["CONSUMER_SECRET"]
	  config.access_token        = ENV["ACCESS_TOKEN"]
	  config.access_token_secret = ENV["ACCESS_SECRET"]
	end

	def user_timeline(qt)
    	@client.user_timeline(count: qt)
  	end
end

app/views/comments/_comment.html.erb
<p><%= content_tag :strong, comment.commenter %></p>
<p><em>created <%= time_ago_in_words(comment.created_at) %> ago</em></p>

<%= content_tag :p, comment.body %>

<%= link_to 'Delete comment', [comment.post, comment], 
        method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |post| %>
  <p>
    <%= post.label :commenter  %><br />
    <%= post.text_field :commenter, :class => 'commenter' %>
  </p>
  <p>
    <%= post.label :body %><br />
    <%= post.text_area :body, cols: 40, rows: 10, :class => 'content' %>
  </p>
  <p>
    <%= post.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<link rel="stylesheet" type="text/css" href="bootstrap.css">
<link rel="stylesheet" type="text/css" href="custom.css">
<meta name="google-site-verification" content="2Yn7trfqMl2n8ACm4mc4qQk6YyHT-jotONx0fdwazZY" />
</head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/jumbotron' %>

    <% flash.each do |type, msg| %>
        <div class="alert <%= flash_class (type) %>">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= msg %>
        </div>
    <% end %>


     <%= yield %>


    <%= render 'shared/footer' %>

  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for (@post) do |post| %>

  <%= render 'shared/errors' %>

  <p>
    <%= post.label :title %><br>
    <%= post.text_field :title, class: 'title' %>
  </p>
 
  <p>
    <%= post.label :content %><br>
    <%= post.text_area :content, cols: 80, rows: 20, class: 'content' %>
  </p>
 
  <p>
    <%= post.submit %>
    <%= link_to 'Back', posts_path %>
  </p>
<% end %>
 

app/views/posts/index.html.erb
<div class="wrap">
  <div class="container panel-body">
    <div class="row">

      <div class="col-xs-6 col-sm-8 content">
        <% @posts.each do |post| %>
        <h4><%= link_to content_tag(:strong, post.title), post %></h4>
        <p>
        <p class="date">
          <%= post.created_at.strftime('%b %d, %Y') %>
        </p>
          <%= truncate(markdown(post.content), length: 300, separator: ' ', escape: false).html_safe %>
          <%= link_to '--Read More--', post %> 
        </p>
        <% end %>
      </div>

      <%= render 'shared/rightsidebar' %> 

    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <div class="form-group">
          <%= form_for (@post) do |post| %>
            
              <%= render 'shared/errors' %>

              <p>
                <%= post.label :title %><br>
                <%= post.text_field :title, :class => "title" %>
              </p>
             
              <p>
                <%= post.label :content %><br>
                <%= post.text_area :content, cols: 80, rows: 20, :class => 'content' %>
              </p>
             
              <p>
                <%= post.submit 'submit' %>
                <%= link_to 'Cancel',  posts_path %>
              </p>
          <% end %>
        </div>
        </div>
    </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">


    <div class="clearfix visible-xs"></div>

    <div class="col-xs-6 col-sm-8">
      <div class="panel panel-default">
        <div class="panel-body content">
          <div class="page-header">
            <p>
              <%= content_tag(:strong, @post.title) %>
            </p>
             <p class="date">
              <%= @post.created_at.strftime('%b %d, %Y') %>
            </p>
            <p><%= markdown(@post.content).html_safe %></p>

            <%= link_to 'Back', posts_path %>
            <%= link_to 'Edit', edit_post_path(@post) %>
            <%= link_to 'Delete', post_path(@post), method: 
            :delete, data: { confirm: 'Are you sure?' }  %>


          <%= render 'shared/disqus' %>

<!--             <h4>Recent Comments:</h4>

            <%= render @post.comments %>

            <h2>Add a comment:</h2>

            <%= render 'comments/form'%> -->

          </div>
        </div>
      </div>
    </div>
    <div class="clearfix visible-xs"></div>
    <%= render 'shared/rightsidebar' %> 
  </div>
</div>


 

app/views/posts/tweets.html.erb
<div class="wrap">
  <div class="container panel-body">
    <div class="row">

      <div class="col-xs-6 col-sm-4">

         <a class="twitter-timeline" href="https://twitter.com/KenyaMoore" data-widget-id="465723657738649601" data-tweet-limit="10">Tweets by @KenyaMoore</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      </div>

      <div class="col-xs-6 col-sm-4">

         <a class="twitter-timeline" href="https://twitter.com/NeNeLeakes" data-widget-id="465746177724399616" data-tweet-limit="10">Tweets by @NeNeLeakes</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      </div>

      <div class="col-xs-6 col-sm-4">
        <a class="twitter-timeline" href="https://twitter.com/PhaedraParks" data-widget-id="465588868905836544" data-tweet-limit="10">Tweets by @PhaedraParks</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      </div>
    </div>
  </div>
</div>



<div class="wrap">
  <div class="container panel-body">
    <div class="row">

      <div class="col-xs-6 col-sm-4">

       <a class="twitter-timeline" href="https://twitter.com/Porsha4real" data-widget-id="465735397830455296" data-tweet-limit="10">Tweets by @Porsha4real</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      </div> 

      <div class="col-xs-6 col-sm-4">
        <a class="twitter-timeline" href="https://twitter.com/CynthiaBailey10" data-widget-id="465746177724399616" data-tweet-limit="10">Tweets by @CynthiaBailey10</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      </div>

      <div class="col-xs-6 col-sm-4">

      </div>

    </div>
  </div>
</div>

app/views/shared/_disqus.html.erb
        

    <div id="disqus_thread"></div>
    <script type="text/javascript">
  
    var disqus_shortname = 'allthingsblog'; 
    var disqus_identifier = <%= @post.id %>;

    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
        
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    
    <script type="text/javascript">
    var disqus_shortname = 'allthingsblog'; 

    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
    </script>

  

app/views/shared/_errors.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

app/views/shared/_footer.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <button type="button" class="btn btn-info">
      <%= link_to 'Home', root_path %>
    </button>
  </div>

</nav>

app/views/shared/_jumbotron.html.erb
<div class="jumbotron">

  <% form_tag posts_path, :method => 'get', :class => 'pull-left' do %>
    <p>search here
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>
  
    <div class="gravatar pull-right">
      <%= image_tag gravatar_for('abdishwak@gmail.com') %>
      <p class="profile-name">Wally Ali</p> 
    </div>
 
</div>

app/views/shared/_leftsidebar.html.erb
<!-- 
<div class="col-xs-6 col-sm-3">
    <div class="list-group-item">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
    </div>
</div> 
-->

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <%= link_to 'All Things Blog', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'New', new_post_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><% link_to 'Register', new_user_registration_path %></li>
        <li><%= edit_profile(current_user) %><li>
        <li><%= login(current_user) %><li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    

app/views/shared/_rightsidebar.html.erb
<div class="right-side col-xs-6 col-sm-4 pull-right">
           <div>
            <iframe width="230" height="500" src="https://www.youtube.com/embed/2Ex8EEv-WPs" frameborder="0" allowfullscreen></iframe>
          </div>
        <h4 class="list-group-item-heading">
          Great Ruby Tutorials</h4>
           
            <p>
                 <%= link_to "Ruby Learning", "http://rubylearning.com/satishtalim/tutorial.html" %> 
            </p>
            <p>
                 <%= link_to "Ruby Monk", "https://rubymonk.com/" %> 
            </p>

            <h4 class="list-group-item-heading">Great Ruby Tutorials</h4>
            <p>
              <%= link_to "Full-Text Search in Rails using elasticsearch", "http://adventuresincoding.com/2012/05/full-text-search-in-rails-using-elasticsearch" %>
            </p>
            
            <h4 class="list-group-item-heading">Mashable's Tech Feeds</h4>
            <p>
              <%= blog_feed %>
            </p>
    </div>
</div>

app/views/shared/_search.html.erb
<% form_tag posts_path, :method => 'get', :class => 'pull-left' do %>
  <p>search here
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>